/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package baseballreservation;

import java.awt.event.WindowAdapter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.plaf.synth.SynthSeparatorUI;
import javax.swing.table.DefaultTableModel;

import org.omg.PortableInterceptor.USER_EXCEPTION;

import jdbc_memo.MemoVO;

/**
 *
 * @author 1class-08
 */
public class Payment extends javax.swing.JFrame {
	PlayDAO playDAO = new PlayDAO();
    /**
     * Creates new form Payment
     */
    public Payment(Main main) {
    	initComponents();
        int play = main.getPlay();
        playinfo = new ArrayList<>();
        switch(play) {
	        case 101: playinfo = playDAO.play_select(play); break;
	        case 107: playinfo = playDAO.play_select(play); break;
	        case 113: playinfo = playDAO.play_select(play); break;
	        case 100: playinfo = playDAO.play_select(play); break;
	        case 106: playinfo = playDAO.play_select(play); break;
	        case 112: playinfo = playDAO.play_select(play); break;
	        case 102: playinfo = playDAO.play_select(play); break;
	        case 108: playinfo = playDAO.play_select(play); break;
	        case 114: playinfo = playDAO.play_select(play); break;
	        case 103: playinfo = playDAO.play_select(play); break;
	        case 109: playinfo = playDAO.play_select(play); break;
	        case 115: playinfo = playDAO.play_select(play); break;
	        case 104: playinfo = playDAO.play_select(play); break;
	        case 110: playinfo = playDAO.play_select(play); break;
	        case 116: playinfo = playDAO.play_select(play); break;
	        case 105: playinfo = playDAO.play_select(play); break;
	        case 111: playinfo = playDAO.play_select(play); break;
	        case 117: playinfo = playDAO.play_select(play); break;
        }
    	pay_lb_day.setText(playinfo.get(0).getPlay_schedule().toString());
    	pay_lb_playnum.setText(playinfo.get(0).getPlay_number_pk()+"");
    	pay_lb_region.setText(playinfo.get(0).getPlay_region_pk());
    	
        pay_combo_red.setEnabled(false);
        pay_combo_sky.setEnabled(false);
        pay_combo_purple.setEnabled(false);
        pay_combo_navy.setEnabled(false);
        pay_combo_green.setEnabled(false);
        
        user = main.getUser();
        seat = new ArrayList<>();
        ticketInfo = new ArrayList<>();
        payInfo = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        pay_chk_red = new javax.swing.JCheckBox();
        pay_combo_red = new javax.swing.JComboBox<>();
        pay_chk_sky = new javax.swing.JCheckBox();
        pay_combo_sky = new javax.swing.JComboBox<>();
        pay_chk_purple = new javax.swing.JCheckBox();
        pay_combo_purple = new javax.swing.JComboBox<>();
        pay_chk_navy = new javax.swing.JCheckBox();
        pay_combo_navy = new javax.swing.JComboBox<>();
        pay_chk_green = new javax.swing.JCheckBox();
        pay_combo_green = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        pay_lb_day = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pay_lb_seat = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pay_lb_price = new javax.swing.JLabel();
        pay_bt_can = new javax.swing.JButton();
        pay_bt_pay = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        pay_chk_card = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        lbBattleDate1 = new javax.swing.JLabel();
        pay_bt_book = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        pay_lb_region = new javax.swing.JLabel();
        pay_lb_playnum = new javax.swing.JLabel();
        pay_bt_bookcan = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        seat_Table = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        
        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/좌석배치도.PNG"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 2, true));

        pay_chk_red.setBackground(new java.awt.Color(255, 0, 51));
        pay_chk_red.setFont(new java.awt.Font("굴림", 1, 14)); // NOI18N
        pay_chk_red.setForeground(new java.awt.Color(255, 0, 51));
        pay_chk_red.setText("red");
        pay_chk_red.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay_chk_redActionPerformed(evt);
            }
        });

        pay_combo_red.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "선택", "1", "2", "3", "4", "5" }));
        pay_combo_red.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay_combo_redActionPerformed(evt);
            }
        });

        pay_chk_sky.setBackground(new java.awt.Color(102, 204, 255));
        pay_chk_sky.setFont(new java.awt.Font("굴림", 1, 14)); // NOI18N
        pay_chk_sky.setForeground(new java.awt.Color(102, 204, 255));
        pay_chk_sky.setText("sky");
        pay_chk_sky.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay_chk_skyActionPerformed(evt);
            }
        });

        pay_combo_sky.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "선택", "6", "7", "8", "9", "10" }));
        pay_combo_sky.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay_combo_skyActionPerformed(evt);
            }
        });

        pay_chk_purple.setBackground(new java.awt.Color(204, 0, 204));
        pay_chk_purple.setFont(new java.awt.Font("굴림", 1, 14)); // NOI18N
        pay_chk_purple.setForeground(new java.awt.Color(204, 0, 204));
        pay_chk_purple.setText("purple");
        pay_chk_purple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay_chk_purpleActionPerformed(evt);
            }
        });

        pay_combo_purple.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "선택", "11", "12", "13", "14", "15" }));
        pay_combo_purple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay_combo_purpleActionPerformed(evt);
            }
        });

        pay_chk_navy.setBackground(new java.awt.Color(0, 0, 102));
        pay_chk_navy.setFont(new java.awt.Font("굴림", 1, 14)); // NOI18N
        pay_chk_navy.setForeground(new java.awt.Color(0, 0, 102));
        pay_chk_navy.setText("nevy");
        pay_chk_navy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay_chk_navyActionPerformed(evt);
            }
        });

        pay_combo_navy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "선택", "16", "17", "18", "19", "20" }));
        pay_combo_navy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay_combo_navyActionPerformed(evt);
            }
        });

        pay_chk_green.setBackground(new java.awt.Color(102, 204, 0));
        pay_chk_green.setFont(new java.awt.Font("굴림", 1, 14)); // NOI18N
        pay_chk_green.setForeground(new java.awt.Color(102, 204, 0));
        pay_chk_green.setText("green");
        pay_chk_green.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay_chk_greenActionPerformed(evt);
            }
        });

        pay_combo_green.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "선택", "21", "22", "23", "24", "25" }));
        pay_combo_green.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay_combo_greenActionPerformed(evt);
            }
        });

        jLabel2.setText("<html><font size=\"7\">VIP</font><font size=\"6\">석</font></html>");

        jLabel3.setText("<html><font size=\"7\">일반</font><font size=\"6\">석</font></html>");

        jLabel4.setText("   색깔별              |      좌석번호");

        jPanel3.setBackground(new java.awt.Color(255, 255, 224));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "결제정보", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("바탕", 0, 14))); // NOI18N

        pay_lb_day.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        pay_lb_day.setForeground(new java.awt.Color(255, 51, 51));
        pay_lb_day.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pay_lb_day.setText("년/월/일");

        jLabel7.setFont(new java.awt.Font("굴림", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("경기일시");

        jLabel8.setFont(new java.awt.Font("굴림", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("선택좌석");

        pay_lb_seat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel10.setFont(new java.awt.Font("굴림", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("결제금액");

        pay_lb_price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        pay_bt_can.setText("취 소");
        pay_bt_can.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay_bt_canActionPerformed(evt);
            }
        });

        pay_bt_pay.setText("결 제");
        pay_bt_pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay_bt_payActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("굴림", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("결제방식");

        pay_chk_card.setBackground(new java.awt.Color(255, 255, 224));
        pay_chk_card.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
        pay_chk_card.setText("신용카드");
        pay_chk_card.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay_chk_cardActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("굴림", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("경기시간");

        lbBattleDate1.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        lbBattleDate1.setForeground(new java.awt.Color(255, 0, 0));
        lbBattleDate1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBattleDate1.setText("오후 5시");

        pay_bt_book.setText("예 매");
        pay_bt_book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay_bt_bookActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("굴림", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("경기장소");

        jLabel14.setFont(new java.awt.Font("굴림", 1, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("경기번호");

        pay_lb_region.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        pay_lb_region.setForeground(new java.awt.Color(255, 0, 51));
        pay_lb_region.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        pay_lb_playnum.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        pay_lb_playnum.setForeground(new java.awt.Color(255, 0, 0));
        pay_lb_playnum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        pay_bt_bookcan.setText("예매취소");
        pay_bt_bookcan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay_bt_bookcanActionPerformed(evt);
            }
        });

        seat_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "경기번호", "선택좌석", "결제금액"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(seat_Table);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lbBattleDate1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pay_lb_seat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pay_lb_price, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pay_lb_day, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pay_lb_region, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pay_lb_playnum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(pay_chk_card)
                                .addGap(31, 31, 31))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(pay_bt_can)
                                .addGap(18, 18, 18)
                                .addComponent(pay_bt_book)
                                .addGap(18, 18, 18)
                                .addComponent(pay_bt_bookcan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pay_bt_pay)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pay_lb_day, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbBattleDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pay_lb_playnum, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pay_lb_region, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pay_lb_seat, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pay_lb_price, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pay_chk_card))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pay_bt_can, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pay_bt_pay, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pay_bt_book, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pay_bt_bookcan, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel10, jLabel7, jLabel8});

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {pay_lb_day, pay_lb_price, pay_lb_seat});

        jLabel12.setText("   색깔별                |      좌석번호");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(pay_chk_red, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pay_chk_sky, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pay_chk_purple, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(pay_combo_sky, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pay_combo_purple, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pay_combo_red, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(pay_chk_green, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pay_chk_navy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pay_combo_navy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pay_combo_green, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pay_chk_red)
                    .addComponent(pay_combo_red, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pay_chk_sky)
                    .addComponent(pay_combo_sky, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pay_chk_purple)
                    .addComponent(pay_combo_purple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pay_chk_navy)
                    .addComponent(pay_combo_navy, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pay_chk_green)
                    .addComponent(pay_combo_green, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {pay_combo_green, pay_combo_navy, pay_combo_purple, pay_combo_red, pay_combo_sky});

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pay_chk_greenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay_chk_greenActionPerformed
    	if(pay_chk_green.isSelected()) {
        	pay_combo_green.setEnabled(true);
        }else {
        	pay_combo_green.setEnabled(false);
        }
    }//GEN-LAST:event_pay_chk_greenActionPerformed

    private void pay_chk_redActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay_chk_redActionPerformed
    	if(pay_chk_red.isSelected()) {
        	pay_combo_red.setEnabled(true);
        }else {
        	pay_combo_red.setEnabled(false);
        }
    }//GEN-LAST:event_pay_chk_redActionPerformed

    private void pay_chk_skyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay_chk_skyActionPerformed
    	if(pay_chk_sky.isSelected()) {
        	pay_combo_sky.setEnabled(true);
        }else {
        	pay_combo_sky.setEnabled(false);
        }
    }//GEN-LAST:event_pay_chk_skyActionPerformed

    private void pay_chk_navyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay_chk_navyActionPerformed
    	if(pay_chk_navy.isSelected()) {
        	pay_combo_navy.setEnabled(true);
        }else {
        	pay_combo_navy.setEnabled(false);
        }
    }//GEN-LAST:event_pay_chk_navyActionPerformed

    private void pay_bt_payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay_bt_payActionPerformed
    	int con = JOptionPane.showConfirmDialog(this, "결제 하시겠습니까?");// Y:0,N:1,C:2
		if (con == 0) {
			if (pay_chk_card.isSelected() && seat_Table.getRowCount() > 0) {
				int idx = user.get(0).getIdx_pk();
				int pay_price = 0;
				for (SeatVO pvo : seat) {
					pay_price += pvo.getSeat_price_fk2();
				}
				int n = playDAO.pay_insert(idx, pay_price);

				payInfo.add(playDAO.pay_select(idx).get(0));
				for (SeatVO svo : seat) {
					ticketInfo.add(playDAO.ticket_select(svo.getPlay_number_fk2(), svo.getSeat_number_fk2()).get(0));
				}

				// payInfo table 생성
				for (TicketVO tvo : ticketInfo) {
					playDAO.payinfo_insert(payInfo.get(0).getPay_number_pk(), tvo.getTicket_number_pk());
				}
				
				pay_chk_card.setSelected(false);
				seat.clear();
				seat_Table.setModel(new DefaultTableModel());
				showMsg(pay_price+"원이 결제되었습니다.");
			}else {
				showMsg("예매 좌석이 없거나 결제 방식이 체크되지 않았습니다.");
			}
		}else{
			showMsg("결제를 취소하셨습니다.");
		}
    }//GEN-LAST:event_pay_bt_payActionPerformed

    private void pay_bt_canActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay_bt_canActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pay_bt_canActionPerformed

    private void pay_chk_cardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay_chk_cardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pay_chk_cardActionPerformed

    private void pay_chk_purpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay_chk_purpleActionPerformed
    	if(pay_chk_purple.isSelected()) {
        	pay_combo_purple.setEnabled(true);
        }else {
        	pay_combo_purple.setEnabled(false);
        }
    }//GEN-LAST:event_pay_chk_purpleActionPerformed

    private void pay_combo_redActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay_combo_redActionPerformed
    	String index = (String)pay_combo_red.getSelectedItem();
    	seat(index);
    }//GEN-LAST:event_pay_combo_redActionPerformed

    private void pay_combo_skyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay_combo_skyActionPerformed
    	String index = (String)pay_combo_sky.getSelectedItem();
    	seat(index);
    }//GEN-LAST:event_pay_combo_skyActionPerformed

    private void pay_combo_purpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay_combo_purpleActionPerformed
    	String index = (String)pay_combo_purple.getSelectedItem();
    	seat(index);
    }//GEN-LAST:event_pay_combo_purpleActionPerformed

    private void pay_combo_navyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay_combo_navyActionPerformed
    	String index = (String)pay_combo_navy.getSelectedItem();
    	seat(index);
    }//GEN-LAST:event_pay_combo_navyActionPerformed

    private void pay_combo_greenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay_combo_greenActionPerformed
    	String index = (String)pay_combo_green.getSelectedItem();
    	seat(index);
    }//GEN-LAST:event_pay_combo_greenActionPerformed
    
    // 좌석 선택
    private void seat(String index) {
    	if(index.equals("선택")) {
    		showMsg("좌석을 선택해주세요.");
    	}else {
    		int seatnum = Integer.parseInt(index);
        	int playnum = Integer.parseInt(pay_lb_playnum.getText());
        	seatinfo = playDAO.seat_select(seatnum,playnum);
        	
        	pay_lb_seat.setText(seatinfo.get(0).getSeat_grade_fk2()+"등급 "+
        						seatinfo.get(0).getSeat_number_fk2()+"번 좌석");
        	pay_lb_price.setText(seatinfo.get(0).getSeat_price_fk2()+"원");
        	
        	pay_chk_red.setSelected(false);
        	pay_chk_sky.setSelected(false);
        	pay_chk_purple.setSelected(false);
        	pay_chk_navy.setSelected(false);
        	pay_chk_green.setSelected(false);
        	pay_combo_red.setEnabled(false);
        	pay_combo_sky.setEnabled(false);
        	pay_combo_purple.setEnabled(false);
        	pay_combo_navy.setEnabled(false);
        	pay_combo_green.setEnabled(false);
    	}
    }

    private void pay_bt_bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay_bt_bookActionPerformed
		if (pay_lb_seat.getText().isEmpty()||pay_lb_seat.getText().equals("")) {
			showMsg("선택한 좌석이 없습니다.");
			return;
		} else {
			int con = JOptionPane.showConfirmDialog(this, "예매 하시겠습니까?");// Y:0,N:1,C:2
			if (con == 0) {
				if(seatinfo.get(0).getSeat_ox_fk2().equals("NO")) {
					int play_number = seatinfo.get(0).getPlay_number_fk2();
					int seat_number = seatinfo.get(0).getSeat_number_fk2();
					
					int n1 = playDAO.seat_ticket(play_number, seat_number,"YES",seatinfo.get(0).getPlay_number_fk2(),
							seatinfo.get(0).getplay_region_fk2(),seatinfo.get(0).getSeat_number_fk2(),
							seatinfo.get(0).getSeat_grade_fk2(),seatinfo.get(0).getSeat_price_fk2(),
							seatinfo.get(0).getPlay_schedule_fk2());
					if(n1>0) {
						seat.add(seatinfo.get(0));
						Object[][] data = new Object[seat.size()][3];
						for (int i = 0; i < seat.size(); i++) {
							data[i][0] = seat.get(i).getPlay_number_fk2();
							data[i][1] = seat.get(i).getSeat_number_fk2();
							data[i][2] = seat.get(i).getSeat_price_fk2();
						}
						
						String[] colNames = {"경기번호", "선택좌석", "결제금액" };
						seat_Table.setModel(new DefaultTableModel(data, colNames) {
							boolean[] canEdit = new boolean[] { false, false, false };

							public boolean isCellEditable(int rowIndex, int columnIndex) {
								return canEdit[columnIndex];
							}
						});
						String str=(n1>0)?"예매 완료!":"예매 실패!";
			        	showMsg(str);
					}
				}else {
					showMsg("좌석이 없습니다.");
				}
				
				seatinfo.remove(0);
				pay_lb_price.setText("");
				pay_lb_seat.setText("");
				return;
			} else {
				showMsg("취소하셨습니다.");
				return;
			}
		}
    	
    }//GEN-LAST:event_pay_bt_bookActionPerformed

    private void showMsg(String string) {
		JOptionPane.showMessageDialog(this, string);
	}

	private void pay_bt_bookcanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay_bt_bookcanActionPerformed
		int con = JOptionPane.showConfirmDialog(this, "예매를 취소하시겠습니까?");// Y:0,N:1,C:2
		if(con==0) {
			for(int i=0;i<seat.size();i++) {
				playDAO.ticket_delete(seat.get(i).getPlay_number_fk2(), 
						seat.get(i).getSeat_number_fk2(),"NO");
			}
			seat.clear();
			seat_Table.setModel(new DefaultTableModel());
			showMsg("모든 예매가 취소되었습니다.");
		}else {
			showMsg("예매 취소가 완료되지 않았습니다.");
		}
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbBattleDate1;
    private javax.swing.JButton pay_bt_book;
    private javax.swing.JButton pay_bt_bookcan;
    private javax.swing.JButton pay_bt_can;
    private javax.swing.JButton pay_bt_pay;
    private javax.swing.JRadioButton pay_chk_card;
    private javax.swing.JCheckBox pay_chk_green;
    private javax.swing.JCheckBox pay_chk_navy;
    private javax.swing.JCheckBox pay_chk_purple;
    private javax.swing.JCheckBox pay_chk_red;
    private javax.swing.JCheckBox pay_chk_sky;
    private javax.swing.JComboBox<String> pay_combo_green;
    private javax.swing.JComboBox<String> pay_combo_navy;
    private javax.swing.JComboBox<String> pay_combo_purple;
    private javax.swing.JComboBox<String> pay_combo_red;
    private javax.swing.JComboBox<String> pay_combo_sky;
    private javax.swing.JLabel pay_lb_day;
    private javax.swing.JLabel pay_lb_playnum;
    private javax.swing.JLabel pay_lb_price;
    private javax.swing.JLabel pay_lb_region;
    private javax.swing.JLabel pay_lb_seat;
    private javax.swing.JTable seat_Table;
    private ArrayList<PlayVO> playinfo;
    private ArrayList<SeatVO> seatinfo;
    private ArrayList<SeatVO> seat;
    private ArrayList<ManagerVO> user;
    private ArrayList<TicketVO> ticketInfo;
    private ArrayList<PayVO> payInfo;
    // End of variables declaration//GEN-END:variables
}
